base: &base
  adapter:  <%= ENV['db_adapter'] %>
  encoding: <%= ENV['db_encoding'] %>
  pool:     <%= ENV['db_pool'] %>
  username: <%= ENV['db_username'] %>

development:
  <<: *base
  database: <%= ENV['db_database'] %>_development

test:
  <<: *base
  database: <%= ENV['db_database'] %>_test

production:
  <<: *base
  database: <%= ENV['db_database'] %>_production
